#HERE WE IMPORT SOME LIBRARIES

In [15]:
import pandas as pd
import numpy as np

#HERE WE IMPORT IRIS FRAMEWORK

In [1]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

#GETTING TO KNOW ABOUT THE KEYS IN IRIS DATASET

In [2]:
print("keys of iris_datasets: {}" .format(iris_dataset.keys()))

keys of iris_datasets: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


#GETTING TO KNOW THE data of 'DESCR'

In [4]:
print(iris_dataset['DESCR'][:193] + "\n...")       #descr = description

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre
...


#ANOTHER WAY TO KNOW THE 'DESCR' DATA

In [7]:
val = iris_dataset['DESCR']
start_val = val[:200]
print(start_val + "\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive
...


#WE KNOW ABOUT THE FLOWERS WE HAVE 

In [8]:
print("Target_names: {}" .format(iris_dataset['target_names']))

Target_names: ['setosa' 'versicolor' 'virginica']


#WE KNOW ABOUT THE FEATURES OF FLOWERS

In [16]:
print("Features_names: {}" .format(iris_dataset['feature_names']))

Features_names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


#WE KNOW THE TYPE OF DATA TYPE IS 'DATA'

In [17]:
print("type of Data: {}" .format(type(iris_dataset['data'])))

type of Data: <class 'numpy.ndarray'>


#WE KNOW ABOUT THE SHAPE OF 'DATA'

In [20]:
print("shape of data: {}" .format(iris_dataset['data'].shape))

shape of data: (150, 4)


#HERE WE SEE THE FIRST FIVE ROWS OF THE 'DATA'

In [23]:
print("first five rows of data : \n {}" .format(iris_dataset['data'][:5]))

first five rows of data : 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


#WE KNOW THE TYPE OF DATATYPE 'TARGET'

In [24]:
print("type of target: {}" .format(type(iris_dataset['target'])))

type of target: <class 'numpy.ndarray'>


#PRINTING THE VALUES IN 'TARGET'

In [25]:
print("Target : {}" .format(iris_dataset['target']))

Target : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


#KNOWING ABOUT THE SHAPE OF 'TARGET'


In [26]:
print("shape of target : {}" .format(iris_dataset['target'].shape))

shape of target : (150,)


#IMPORTING THE ANOTHER LIBRARY

In [7]:
import sklearn
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'], random_state=0)

In [8]:
print("X_train shape: {}" .format(X_train.shape))
print("y_train shape: {}" .format(y_train.shape))
print("X_test shape: {}" .format(X_test.shape))
print("y_test shape: {}" .format(y_test.shape))

X_train shape: (112, 4)
y_train shape: (112,)
X_test shape: (38, 4)
y_test shape: (38,)


#K-NEAREST NEIGHBORS MACHINE LEARNING MODEL CREATED

In [10]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

#HERE WE TRAIN THE MODEL

In [13]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm = 'auto', leaf_size = 30, metric = 'minkowski',
                         metric_params = None, n_jobs = None, n_neighbors = 1, p=2,
                         weights = 'uniform')

KNeighborsClassifier(n_neighbors=1)

#TESTING THE KNOWLEDGE OF THE MODEL WE HAVE CREATED


In [16]:
X_new = np.array([[5, 5.3, 7, 0.2]])  #two [[]] for representing the 2-d array
print("X_new.shape: {}" .format(X_new.shape))

X_new.shape: (1, 4)


#MAKING PREDICTIONS FOR TYPE OF FLOWERR

In [18]:
prediction = knn.predict(X_new)

print("Prediction : {}" .format(prediction))
print("Predicted target name: {}" .format(
iris_dataset['target_names'][prediction]))

Prediction : [2]
Predicted target name: ['virginica']


#EVALUATING THE MODEL i.e LOOKING THE TEST DATASET 

In [19]:
y_pred = knn.predict(X_test)
print("Test set predictions: \n {}" .format(y_test))

Test set predictions: 
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1]


#CHECK PREDICTED VALUES ARE TRUE OR FALSE


In [20]:
print("Test set score: {}" .format(np.mean(y_pred == y_test)))

Test set score: 0.9736842105263158
